print('Tämä ohjelma laskee neljän tenttiarvosanan keskiarvon.')
eka = float(input('Anna 1. tenttiarvosana väliltä 0-5: '))
toka = float(input('Anna 2. tenttiarvosana väliltä 0-5: '))
kolmas = float(input('Anna 3. tenttiarvosana väliltä 0-5: '))
neljäs = float(input('Anna 4. tenttiarvosana väliltä 0-5: '))
summa = int((eka+toka+kolmas+neljäs))
keskiarvo = float(((eka+toka+kolmas+neljäs)/4))
keskiarvo2 = round(keskiarvo, 1)
kokonaisluku = round(keskiarvo)
print('')
print ('Antamiesi arvosanojen summa on', str(summa) + '.')
print ('Antamiesi arvosanojen keskiarvo on', str(keskiarvo2) + '.')
print ('Keskiarvo on kokonaislukuna', str(kokonaisluku) + '.')
print ('Kiitos ohjelman käytöstä.')
